version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  build_project:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install pip==23.3.2
      - run:
          name: Change directory and install dependencies
          command: pip install -t lib -r requirements.txt
      - run:
          name: Create deployment package
          command: |
            mkdir -p package
            cp -r lib/* package/
            cp -r api package/
            cp main.py package/
            cd package
            zip -r ../lambda_function.zip .
      - run:
          name: List files in current directory
          command: ls -R
      - persist_to_workspace:
          root: .
          paths:
            - lambda_function.zip
  
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List files in current directory after attaching workspace
          command: ls -R
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy to Lambda
          command: aws lambda update-function-code --function-name imaginari-fastapi --zip-file fileb://lambda_function.zip

workflows:
  deploy-to-lambda:
    jobs:
      - build_project
      - deploy_project:
          requires:
            - build_project
